/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBTRFLY, IBTRFLYInterface } from "../IBTRFLY";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBTRFLY__factory {
  static readonly abi = _abi;
  static createInterface(): IBTRFLYInterface {
    return new utils.Interface(_abi) as IBTRFLYInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBTRFLY {
    return new Contract(address, _abi, signerOrProvider) as IBTRFLY;
  }
}
